### ISSUE TITLE
Hacktoberfest 2019 

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/BlockBall#237]
### Hacktoberfest 2019

This project needs some help with minor refactoring changes.
If you are a OpenSource contributor, you have found a project which provides explained and easy tasks for you :)

### Guidlines

**Required Knowledge**
* Java/Kotlin
* Common knowledge about the Bukkit API

**Code/Style/Architecture**
* Please use the existing layout of the project and avoid creating packages.
* Keep consistency over the whole project.

### Getting started

* Look for a task below which you would like to do
* Create a new issue with the task name and label Hacktoberfest
* Fork and clone the repository to your local pc
* Use the [contributing description](https://github.com/Shynixn/BlockBall#contributing) on the README to setup required dependencies in order to build the project.
* Work on it :)
* Submit a pull request when you are done to initiate a reviewing process

### Tasks

**It is highly recommend to create a new issue on this project with the task name for example "Refactor convertChatColors" to avoid duplicate task pull requests.**

### Open Tasks

No open tasks ~

### Completed Tasks

- [x] Refactor TemplateServiceImpl  - Thanks to mattyway
* The class `com.github.shynixn.blockball.bukkit.logic.business.service.TemplateServiceImpl` can be refactored to no longer depend on org.bukkit.* imports and should be moved to the cross platform module blockball-core
* Move the class com.github.shynixn.blockball.bukkit.logic.business.service.TemplateServiceImpl to the com.github.shynixn.blockball.core.logic.business.service package
* Instead of using `Plugin` you can access the application directory and resources via the `ConfigurationService` (add it as constructor dependency)
* Instead of using `YamlConfiguration` you can use the `YamlService` to read data from files (add it as constructor dependency)
* Make sure to especially simplify the `getAvailableTemplates` function   https://github.com/Shynixn/BlockBall/blob/95e91cde65dd011a219b71145d97eb78f8b1914b/blockball-bukkit-plugin/src/main/java/com/github/shynixn/blockball/bukkit/logic/business/service/TemplateServiceImpl.kt#L55
* Make sure the project still compiles afterwards

- [x] Refactor VirtualArenaServiceImpl - Thanks to archery2000 
* The class com.github.shynixn.blockball.bukkit.logic.business.service.VirtualArenaServiceImpl can be easily refactored to no longer depend on org.bukkit.* imports and should be moved to the cross platform module blockball-core
* Move the class com.github.shynixn.blockball.bukkit.logic.business.service.VirtualArenaServiceImpl to the com.github.shynixn.blockball.core.logic.business.service package
* Instead of using ``plugin.server.scheduler.runTaskAsynchronously(plugin, {})`` you can use ``        async(concurrencyService){}``
* Make sure the project still compiles afterwards

- [x] Remove SpigotTiming - Thanks to rbrick
* The class com.github.shynixn.blockball.bukkit.logic.business.service.SpigotTimingServiceImpl and com.github.shynixn.blockball.api.business.service.SpigotTimingService are no longer needed and have to get removed
* Make sure to delete both classes and remove all usages across the whole project
* Make sure the project still compiles afterwards

- [x] Refactor findClazz - Thanks to davidegavio 
* Replace all useages of findClazz($name,$plugin) extension method with [findClazz($name)](https://github.com/Shynixn/BlockBall/blob/8f47088d7fbdb0510d952be78315bc04949d5764/blockball-bukkit-plugin/src/main/java/com/github/shynixn/blockball/bukkit/logic/business/extension/ExtensionMethods.kt#L276)
* Remove the [findClazz($name,$plugin)](https://github.com/Shynixn/BlockBall/blob/8f47088d7fbdb0510d952be78315bc04949d5764/blockball-bukkit-plugin/src/main/java/com/github/shynixn/blockball/bukkit/logic/business/extension/ExtensionMethods.kt#L269) method afterwards
* Make sure the project still compiles afterwards

- [x] Refactor convertChatColors - Thanks to abhi2196
* Replace all useages of [convertChatColors](https://github.com/Shynixn/BlockBall/blob/8f47088d7fbdb0510d952be78315bc04949d5764/blockball-bukkit-plugin/src/main/java/com/github/shynixn/blockball/bukkit/logic/business/extension/ExtensionMethods.kt#L228) extension method with [translateChatColors](https://github.com/Shynixn/BlockBall/blob/8f47088d7fbdb0510d952be78315bc04949d5764/blockball-core/src/main/java/com/github/shynixn/blockball/core/logic/business/extension/ExtensionMethod.kt#L68). 
* Remove the method [convertChatColors](https://github.com/Shynixn/BlockBall/blob/8f47088d7fbdb0510d952be78315bc04949d5764/blockball-bukkit-plugin/src/main/java/com/github/shynixn/blockball/bukkit/logic/business/extension/ExtensionMethods.kt#L228)
* Make sure the project still compiles afterwards

**Comment by Shynixn** [comment]
I have updated BlockBall master that travisCI no longer fails.

**Comment by archery2000** [comment]
Sure! I'll get to work

**Comment by archery2000** [comment]
What environment is used to execute the commands stated on contribution steps?
When I tried to run "gradle sync" in Gradle 5.6.2, it provided me with a warning of deprecated methods as well as an error:

> Task "sync" not found in root project blockball_root

Am I doing something wrong in setting up the project workspace?

**Comment by Shynixn** [comment]
``gradle build`` will normally do the job for you.

**Comment by archery2000** [comment]
I get the following error when running `gradle build`

> Could not find org.spigotmc:spigot18R3:1.8.8-R3.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/spigotmc/spigot18R3/1.8.8-R3.0/spigot18R3-1.8.8-R3.0.pom
       - https://repo.maven.apache.org/maven2/org/spigotmc/spigot18R3/1.8.8-R3.0/spigot18R3-1.8.8-R3.0.jar
       - file:/C:/Users/ongyu/.m2/repository/org/spigotmc/spigot18R3/1.8.8-R3.0/spigot18R3-1.8.8-R3.0.pom
       - file:/C:/Users/ongyu/.m2/repository/org/spigotmc/spigot18R3/1.8.8-R3.0/spigot18R3-1.8.8-R3.0.jar
       - https://jcenter.bintray.com/org/spigotmc/spigot18R3/1.8.8-R3.0/spigot18R3-1.8.8-R3.0.pom
       - https://jcenter.bintray.com/org/spigotmc/spigot18R3/1.8.8-R3.0/spigot18R3-1.8.8-R3.0.jar
       - https://repo.spongepowered.org/maven/org/spigotmc/spigot18R3/1.8.8-R3.0/spigot18R3-1.8.8-R3.0.pom
       - https://repo.spongepowered.org/maven/org/spigotmc/spigot18R3/1.8.8-R3.0/spigot18R3-1.8.8-R3.0.jar
     Required by:
         project :petblocks-tools


and the following error when running `gradlew.bat downloadDependencies`
`Exception in thread "main" java.lang.RuntimeException: Error running command, return status !=0: [sh, /mnt/d/Documents/Workspace/PetBlocks/build/buildtools/apache-maven-3.6.0/bin/mvn, clean, install]
        at org.spigotmc.builder.Builder.runProcess0(Builder.java:771)
        at org.spigotmc.builder.Builder.runProcess(Builder.java:706)
        at org.spigotmc.builder.Builder.main(Builder.java:548)
        at org.spigotmc.builder.Bootstrap.main(Bootstrap.java:40)`

How may I fix this? Apologies if this is a simple mistake, I haven't used gradle before.

**Comment by Shynixn** [comment]
Hm... it works on my machine (windows) and on the CI build server (linux). You can try the following:
* Install git on your machine 
* Delete the .../BlockBall/build/buildtools folder
* Run ``gradle downloadDependencies``, if successful run ``gradle build``

**Comment by archery2000** [comment]
hmm, still doesn't work. I'm using Java SDK 1.8.0_231, with Git for Windows v2.22.0 on Windows 10. It seems that the problem comes from downloading and compiling spigot. I compiled spigot separately, will see if it suffices.

**Comment by archery2000** [comment]
Got it to work. For the unit tests, since I'm passing player as a generic type <P>, should I still keep the unit test checking player validity? If I keep it, I'll include a call to getPlayerName in ProxyService so that ProxyService can throw the exception if necessary

**Comment by Shynixn** [comment]
Nice, what was the problem?

The ``displayForPlayers_InvalidPlayer_ShouldThrowException`` test is no longer needed. You can remove it.

**Comment by archery2000** [comment]
Opened a pull request at #248 to close the corresponding issue #247.

I'm still not too sure what the problem is, honestly. Indeed the problem is with retrieving the different spigot jars. Even when I get the buildtools jar from the spigot website directly, copying it into the folder and running the command doesn't work. Perhaps, it has something to do with workspace placement, if it isn't in the same drive as the OS, there appears to be some issue?

Regardless, the workaround I managed was to run the commands in C:\ first, then copy the jars over to the buildtools folder before running the remainder of the commands. After that, building works fine. @Shynixn

**Comment by Shynixn** [comment]
I see thanks. Maybe I can adjust the gradle task to be more reliable.

**Comment by Shynixn** [comment]
Added a new task!
