### ISSUE TITLE
Hacktoberfest 2020

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/BlockBall#320]
### Hacktoberfest 2020 [Thanks to everyone who contributed to this project last year]

This project needs some help with minor refactoring changes.
If you are a OpenSource contributor, you have found a project which provides explained and easy tasks for you :)

### Guidlines

**Required Knowledge**
* Java/Kotlin

**Optional Knowledge**
* Common knowledge about the Bukkit API

**Code/Style/Architecture**
* Please use the existing layout of the project and avoid creating packages.
* Keep consistency over the whole project.

### Getting started

* Look for a task below which you would like to do
* Create a new issue with the task name
* Fork and clone the repository to your local pc
* Use the [contributing description](https://github.com/Shynixn/BlockBall#contributing) on the README to setup required dependencies in order to build the project.
* Work on it :)
* Submit a pull request to the ``hacktoberfest-2020`` branch when you are done to initiate a reviewing process

### Tasks

:exclamation: It is **highly recommend** to create a new issue on this project with the task name for example "Refactor convertChatColors" to **avoid duplicate task pull requests**. :exclamation:

##### Can I take more than 1 task? 

Yes, but only 1 task at a time. **After your first pull request has been approved**, you can take the second task.

##### How long does it take to get feedback on a pull request?

I normally check daily for new activity on this repository.

##### I am not able to setup the project environment?

Just message me below this issue.

### Open Tasks

- [x] Refactor arena selection ~ Thanks to @nlaert
* The BlockBall plugin offers a way to select an arena via WorldEdit. However, this feature has been replaced by an own selection algorithm and is not being used anymore. 
* Remove ``com.github.shynixn.blockball.api.business.service.DependencyWorldEditService`` and all implementations of it.
* Modify ``com.github.shynixn.blockball.bukkit.logic.business.service.BlockSelectionServiceImpl`` so that it no longer uses  ``com.github.shynixn.blockball.api.business.service.DependencyWorldEditService``. You can start by removing the ``isBlockBallAxeEnabled()`` function and assuming everywhere where it has been called before, it is now always true.
* Make sure to remove any other usages of the  ``com.github.shynixn.blockball.api.business.service.DependencyWorldEditService`` across the project
* Make sure the project still compiles afterwards and passes all tests.

- [x] Refactor PackageService ~ Thanks to @Giancarmine
* The functionality of the PackageService should be move to the ProxyService.
* Move the function ``sendPacket`` from the ``com.github.shynixn.blockball.api.business.service.PackageService`` class to ``com.github.shynixn.blockball.api.business.service.ProxyService``. (including all implementaions)
* Remove ``com.github.shynixn.blockball.api.business.service.PackageService`` and all implementations of it.
* Replace all calls to the ``$PackageService.sendPacket`` function with calls to the ``$ProxyService.sendPacket`` function.
* Make sure the project still compiles afterwards and passes all tests.

- [x] Refactor RightclickManageServiceImpl ~ Thanks to @Giancarmine
* This service can be refactored from the ``blockball-bukkit-plugin`` module to the ``blockball-core`` module.
* Move the class ``com.github.shynixn.blockball.bukkit.logic.business.service.RightclickManageServiceImpl`` class to 
``com.github.shynixn.blockball.core.logic.business.service.RightclickManageServiceImpl``
* Remove all ``org.bukkit.*`` dependencies. The type of the method parameters does not need to be checked. 
* Instead of ``Player`` use ``Any``
* Add a constructor dependency to ``ProxyService`` (take a look at other classes to find out how to do that).
* Use the  ``$ProxyService.setSignLines`` method to set the sign lines. (The boolean return value might be useful)
* Make sure the project still compiles afterwards and passes all tests.

- [ ] Fix documentation spelling errors
* The [BlockBall wiki](https://shynixn.github.io/BlockBall/build/html/index.html ) contains some major and minor spelling errors. 
* Read through the **.rst** source files in [this folder](https://github.com/Shynixn/BlockBall/tree/master/docs/source) which are being used to create the **.html** files automatically .
* Correct as many mistakes in the **.rst** files as you can find, please search for more than 1 issue, so it makes sense to open a pull request. 

- [ ] Implement issue #329 
* You do not need to create a new issue for this issue. Just comment on #329 to take this task. 
* This task really requires you to get into the details of BlockBall, so it is not for beginners. 
* You can find the task description on the issue description.

- [.. ] More tasks to be added once the tasks are above have been completed.

### Completed Tasks

~

**Comment by erwinkaaa** [comment]
Hi. I'm new to open source. I would like to try to contribute to this!

**Comment by Shynixn** [comment]
Hi @erwinkaaa!

Sure, go ahead and perform the actions in the "Getting started" section.

**Comment by Shynixn** [comment]
Updated the topic of this repository to participate in Hacktoberfes.

**Comment by Shynixn** [comment]
Thanks for all contribution. This Hacktoberfest issue tracker will be closed.
